/** Hebrew UI copy (ported from legacy i18n.js STRINGS.he). */
export const heStrings: Record<string, string> = {
  "auth.title.login": "התחברות",
  "auth.title.register": "יצירת חשבון",
  "auth.subtitle.login": "הזינו אימייל וסיסמה כדי לגשת לתיק.",
  "auth.subtitle.register": "הזינו אימייל וסיסמה תקפים. מנהל חייב לאשר חשבונות חדשים.",
  "auth.email": "אימייל",
  "auth.emailPlaceholder": "you@example.com",
  "auth.password": "סיסמה",
  "auth.submit.login": "התחברות",
  "auth.submit.register": "יצירת חשבון",
  "auth.toggle.toRegister": "יצירת חשבון",
  "auth.toggle.toLogin": "כבר יש לכם חשבון? התחברות",
  "auth.forgotNote": "שכחתם סיסמה? התחברו עם חשבון חדש או בקשו ממנהל לאפס במסד הנתונים.",
  "auth.viewTour": "חדשים כאן? צפו בסיור קצר ←",
  "auth.betaBadge": "בטא פרטית",
  "auth.betaNotice": "<strong>בטא פרטית.</strong> זהו פרויקט פיתוח אישי בשלב בדיקות סגור, מסופק \"כפי שהוא\" (as-is) ללא התחייבות לזמינות. הגישה ניתנת רק לאחר אישור מנהל. תכונות עשויות להשתנות והנתונים עלולים להימחק מדי פעם במהלך עדכונים. אנא אל תשמרו מידע רגיש במיוחד (סיסמאות בנק אמיתיות, מספרי תעודת זהות וכד׳).",
  "auth.error.signInFailed": "ההתחברות נכשלה",
  "auth.error.registerFailed": "ההרשמה נכשלה",
  "auth.toast.accountCreated": "החשבון נוצר. מנהל חייב לאשר לפני התחברות.",
  "hero.eyebrow": "ענן · פרטי · מוגן בסיסמה",
  "hero.title": "מעקב חיסכון",
  "hero.subtitle": "מחברת תיק אישית לקופות גמל/השתלמות (גמלנט), מענקי RSU, ESPP ומזומן — למעקב פרטי, לא לשימוש מקצועי.",
  "disclaimer.aria": "הבהרות חשובות",
  "disclaimer.compact": "בטא פרטית · כלי אישי — לא ייעוץ פיננסי.",
  "disclaimer.title": "חשוב — קראו לפני השימוש",
  "nav.aria": "ניווט בין חלקים",
  "disclaimer.item.beta": "<strong>בטא פרטית.</strong> זהו פרויקט אישי בשלב בדיקות סגור, מסופק \"כפי שהוא\" (as-is) ללא התחייבות לזמינות. תכונות עשויות להשתנות והנתונים עלולים להימחק מדי פעם במהלך עדכונים. אנא אל תשמרו מידע אישי או פיננסי רגיש במיוחד (כגון סיסמאות בנק אמיתיות או מספרי תעודת זהות).",
  "disclaimer.item.personalUse": "<strong>לשימוש אישי בלבד.</strong> זו אפליקציית תחביב למעקב אחר החיסכון שלכם. זו אינה מוצר מסחרי, שירות פיננסי מוסדר או תחליף ליועץ מוסמך.",
  "disclaimer.item.notAdvice": "<strong>לא ייעוץ פיננסי, השקעות, מס או משפטי.</strong> כל המספרים, הגרפים והתחזיות הם הערכות מידעיות בלבד. אל תקבלו החלטות רק על סמך האפליקציה.",
  "disclaimer.item.noTax": "<strong>אין חישוב מס.</strong> המספרים הם לפני מס ובערכים נומינליים. כללי המס בישראל אינם מחושבים באפליקציה — התייעצו עם מנהל הקופה, רואה חשבון או רשות המסים.",
  "disclaimer.item.dataStale": "<strong>הנתונים עלולים להיות שגויים או לא מעודכנים.</strong> תשואות מגיעות מ-data.gov.il; מחירי מניות ושערי חליפין מ-Yahoo. תמיד אמתו מול דוחות רשמיים.",
  "disclaimer.item.projections": "<strong>תחזיות אינן הבטחה.</strong> ביצועי עבר ושיעורי צמיחה משוערים אינם מבטיחים תוצאות עתידיות. תרחישי what-if הם מודלים מפושטים.",
  "disclaimer.item.ownRisk": "<strong>השימוש באחריותכם.</strong> אין אחריות לנזקים או החלטות הנובעים משימוש בתוכנה.",
  "disclaimer.item.responsibility": "<strong>אחריותכם.</strong> אתם אחראים לדיוק הנתונים שהזנתם ולאבטחת פרטי ההתחברות. חשבונות חדשים דורשים אישור מנהל.",
  "status.loading": "טוען…",
  "status.wakingServer": "מעיר את השרת…",
  "status.syncing": "מסנכרן…",
  "status.synced": "סונכרן",
  "status.loadedUsdils": "נטען · USDILS {rate}",
  "status.failedLoad": "טעינת הנתונים נכשלה",
  "status.syncFailed": "הסנכרון נכשל",
  "status.yields": "תשואות · {label}",
  "chrome.langToggle": "שפה",
  "chrome.aiChat": "צ׳אט AI",
  "chrome.hideAi": "הסתר AI",
  "chrome.openAiChat": "פתח צ׳אט AI",
  "chrome.toggleTheme": "החלף מצב בהיר/כהה",
  "chrome.signOut": "התנתקות",
  "chrome.refresh": "↻ רענון",
  "common.cancel": "ביטול",
  "common.save": "שמירה",
  "common.show": "הצג",
  "common.hide": "הסתר",
  "common.gotIt": "הבנתי",
  "common.details": "פרטים",
  "common.confirm": "אישור",
  "common.failed": "נכשל",
  "common.updated": "עודכן",
  "common.deleted": "נמחק",
  "help.aboutSection": "מה זה החלק הזה?",
  "section.dashboard": "לוח בקרה",
  "section.funds": "קופות",
  "section.pension": "פנסיה",
  "section.retirementSim": "סימולטור פרישה",
  "section.rsu": "מענקי RSU",
  "section.espp": "תוכניות ESPP",
  "section.cash": "מזומן ולא מושקע",
  "section.settings": "הגדרות",
  "funds.add": "+ הוספת קופה",
  "pension.add": "+ הוספת פנסיה",
  "rsu.add": "+ הוספת מענק",
  "espp.add": "+ הוספת תוכנית",
  "cash.add": "+ הוספת מזומן",
  "pension.subtotal": "סכום ביניים",
  "pension.excludedFromTotal": "לא נכלל בסך הכולל",
  "dashboard.horizon": "אופק:",
  "dashboard.range": "טווח",
  "dashboard.resetRange": "איפוס טווח",
  "dashboard.whatIfGrow": "אם הקופות צומחות %/שנה:",
  "dashboard.whatIfGrowTitle": "חל על קופות בלבד. מזומן, הבשלת RSU ו-ESPP מתווספים באופן קבוע מעל.",
  "dashboard.whatIfInputTitle": "שיעור צמיחה שנתי החל על קופות בלבד. מזומן, הבשלת RSU ו-ESPP מתווספים באופן קבוע מעל — הם אינם צוברים ריבית בשיעור זה.",
  "dashboard.whatIfHint": "קופות בלבד · מזומן + RSU + ESPP קבועים",
  "dashboard.allocation": "הקצאה",
  "alloc.concentrated": "{pct}% מהסך הכולל שלך נמצאים ב{label}.",
  "insights.title": "תובנות AI",
  "insights.loading": "מנתח את התיק שלך…",
  "insights.refresh": "רענון תובנות",
  "insights.error": "התובנות אינן זמינות כרגע.",
  "insights.updated": "עודכן {ago}",
  "insights.disclaimer": "נוצר על ידי AI מהנתונים שלך — לא ייעוץ פיננסי.",
  "dashboard.pensionNote": "<span>🔒</span><span><strong>פנסיה ({amount})</strong> מנוהלת בנפרד למטה — לא נכללת בסך זה או בגרף. הנחת הצמיחה למעלה עדיין חלה עליה, לפי שורה.</span>",
  "dashboard.caption": "ברירת המחדל מציגה את שני החודשים האחרונים בתוספת האופק שבחרתם. גררו אופקית בגרף או בחרו חודשי התחלה/סיום למיקוד — כל חודש אפשרי: חודשים בעבר מושכים היסטוריה, ובחירה רחוקה בעתיד מרחיבה אוטומטית את התחזית (עד 50 שנה). לחצו Esc תוך כדי גרירה לביטול; לחצו על שבב אופק לאיפוס.",
  "chat.title": "צ׳אט על התיק",
  "chat.panelAria": "צ׳אט AI על התיק",
  "chat.clear": "ניקוי",
  "chat.clearTitle": "נקה שיחה",
  "chat.close": "סגור צ׳אט",
  "chat.disclaimer": "<strong>הבהרת צ׳אט AI.</strong> התשובות נוצרות על ידי Google Gemini מסיכום נתוני התיק. ללימוד אישי בלבד — לא ייעוץ פיננסי, מס, השקעות או משפטי. המספרים עלולים להיות חלקיים או שגויים; אמתו מול דוחות רשמיים. הודעות והקשר נשלחים ל-API של Google. השימוש באחריותכם.",
  "chat.empty": "שאלו על החזקות, תשואות, פיזור או איך לשפר.",
  "chat.placeholder": "שאלו על התיק…",
  "chat.send": "שליחה",
  "chat.sendAria": "שלח הודעה",
  "chat.suggestionsAria": "שאלות מוצעות",
  "chat.chip.features": "מה אפשר לעשות באפליקציה?",
  "chat.chip.concentration": "איפה הריכוז שלי?",
  "chat.chip.improve": "איך לשפר את הפיזור?",
  "chat.chip.project": "תחזית ל{proj} ב־8%",
  "chat.prompt.features": "מה אפשר לעשות באפליקציה הזו? סכמו את היכולות העיקריות ואיך להשתמש בהן עם התיק שלי.",
  "chat.prompt.concentration": "איפה אני מרוכז בין קופות, RSU, ESPP ומזומן?",
  "chat.prompt.improve": "הציעו שיפורים קונקרטיים לפי הפיזור, ההפקדות וההבשלה שלי.",
  "chat.prompt.project": "אם הקופות צומחות ב־8% לשנה, מה הסך החזוי והשינוי מול היום ב{proj}?",
  "chat.role.you": "את/ה",
  "chat.role.assistant": "עוזר AI",
  "chat.thinking": "חושב…",
  "chat.disabled": "הצ׳אט מושבת בשרת.",
  "chat.sorry": "מצטער — לא הצלחתי לענות ({error}).",
  "settings.appearance": "מראה",
  "settings.theme.system": "מערכת (לפי המכשיר)",
  "settings.theme.light": "בהיר",
  "settings.theme.dark": "כהה",
  "settings.netOfFees": "ברירת מחדל: MONTHLY_YIELD נטו מעמלות",
  "settings.usdilsOverride": "דריסת שער USDILS",
  "settings.usdilsPlaceholder": "השאירו ריק לשימוש ב-Yahoo",
  "settings.exportJson": "ייצוא JSON",
  "settings.importJson": "ייבוא JSON",
  "settings.changePassword": "שינוי סיסמה",
  "settings.clearCache": "ניקוי מטמון",
  "settings.dangerZone": "<strong>אזור מסוכן</strong> — פעולות בלתי הפיכות",
  "settings.deleteAccount": "מחיקת החשבון שלי",
  "settings.deleteAccountBlurb": "מוחק לצמיתות את ההתחברות ואת <strong>כל הנתונים האישיים</strong> במסד (החזקות, מענקים, מזומן, הגדרות ומחירי מטמון). לא ניתן לבטל.",
  "toast.synced": "סונכרן מ-data.gov.il + Yahoo",
  "toast.syncFailed": "הסנכרון נכשל",
  "toast.sessionExpired": "פג תוקף ההתחברות. התחברו שוב.",
  "toast.exported": "הנתונים יוצאו",
  "toast.imported": "הנתונים יובאו",
  "toast.invalidJson": "JSON לא תקין",
  "toast.passwordUpdated": "הסיסמה עודכנה",
  "toast.passwordsMismatch": "הסיסמאות החדשות אינן תואמות",
  "toast.cacheCleared": "המטמון נוקה. לחצו רענון לסנכרון מחדש.",
  "toast.accountDeleted": "החשבון נמחק.",
  "toast.fundAdded": "הקופה נוספה",
  "toast.pensionAdded": "הפנסיה נוספה",
  "toast.grantAdded": "המענק נוסף",
  "toast.esppAdded": "תוכנית ESPP נוספה",
  "toast.cashAdded": "המזומן נוסף",
  "help.dashboard.title": "על לוח הבקרה",
  "help.chat.title": "על צ׳אט AI",
  "help.funds.title": "על קופות",
  "help.pension.title": "על פנסיה",
  "help.retirementSim.title": "על סימולטור פרישה",
  "help.rsu.title": "על מענקי RSU",
  "help.espp.title": "על תוכניות ESPP",
  "help.cash.title": "על מזומן ולא מושקע",
  "help.settings.title": "על הגדרות",
  "rsim.intro": "הערכת פנסיה מול משיכה חד־פעמית בפרישה לפי כללי ישראל מפושטים ל־2026. שום דבר כאן לא נשמר לחשבון.",
  "rsim.birthDate": "תאריך לידה",
  "rsim.gender": "מגדר",
  "rsim.gender.male": "זכר (גבר)",
  "rsim.gender.female": "נקבה (אישה)",
  "rsim.retirementAge": "גיל פרישה",
  "rsim.comprehensive": "יתרת מקיפה בפרישה (₪)",
  "rsim.supplementary": "יתרת משלימה בפרישה (₪, אופציונלי)",
  "rsim.targetPension": "יעד פנסיה חודשית — מסלול 3 (₪)",
  "rsim.note": "הערכה מידעית בלבד — לא ייעוץ מס או פיננסי.",
  "help.dashboard.body": "<p>המספר הגדול הוא <strong>סך התיק</strong> בשקלים — קופות + RSU + ESPP + מזומן.</p>\n<p>הגרף המרובד מסתכל קדימה מהחודש הנוכחי. <code>אם הקופות צומחות %/שנה</code> חל על קופות (והפקדות) בלבד; מזומן, הבשלת RSU ו-ESPP נשארים קבועים.</p>\n<p><strong>שבבי אופק</strong> וטווח תאריכים (גרירה או בחירת חודשים) קובעים עד כמה רחוק ואיזה קטע רואים.</p>\n<p>תחזיות הן הערכות בלבד — לא ייעוץ.</p>",
  "help.chat.body": "<p>עוזר אופציונלי מבוסס <strong>Google Gemini</strong>. נפתח כפאנל בצד ימין עם סיכום התיק.</p>\n<p>פתיחה עם <strong>צ׳אט AI</strong> (מחשב) או כפתור <strong>AI</strong> הצף (מובייל). ההיסטוריה נשמרת רק לסשן — <strong>ניקוי</strong> מאפס.</p>\n<p><strong>לא ייעוץ.</strong> התשובות עלולות להיות שגויות. הודעות והקשר נשלחים ל-API של Google.</p>",
  "help.funds.body": "<p>קופות גמל / השתלמות ופוליסות חיסכון מ-<code>data.gov.il</code>.</p>\n<p>לכל החזקה יש <strong>תקופת עוגן</strong> ו<strong>יתרת עוגן</strong>; האפליקציה מצמידה לפי <code>MONTHLY_YIELD</code> שפורסם.</p>\n<p>כללי הפקדה חוזרים לעובד/מעסיק ואירועים ידניים לחד־פעמיים. הערכת עמלות למידע בלבד — התשואות בדרך כלל כבר נטו.</p>",
  "help.pension.body": "<p>קרנות פנסיה מ-pensia-net. נעולות עד פרישה ו<strong>לא נכללות בסך לוח הבקרה</strong>.</p>\n<p>אותו מנגנון עוגן + תשואה כמו בקופות, כולל הפקדות חוזרות. what-if לפי הנחת הצמיחה בלוח, לפנסיה בלבד.</p>\n<p><strong>האפליקציה אינה מחשבת מס ישראלי.</strong></p>",
  "help.retirementSim.body": "<p>כלי what-if עצמאי למשיכת פנסיה בפרישה (כללי 2026). <strong>לא מקושר</strong> להחזקות ו<strong>לא נשמר</strong>.</p>\n<p>הזינו יתרות מקיפה / משלימה, תאריך לידה, מגדר וגיל פרישה להשוואת מסלולים. מודל המס מפושט.</p>",
  "help.rsu.body": "<p>מעקב אחרי טיקר, תאריך מענק, מניות ולוח הבשלה. מחירים ושער מ-Yahoo.</p>\n<p><strong>מוחזק = הבשיל − נמכר</strong>. רשמו מכירות לרווח ממומש; בסיס עלות ברירת מחדל הוא מחיר הסגירה ביום המענק.</p>\n<p><strong>האפליקציה אינה מחשבת מס ישראלי.</strong></p>",
  "help.espp.body": "<p>תוכנית רכישת מניות לעובדים: הנחה, lookback, אורך מחזור ורכישות.</p>\n<p>הנחה שנתפסה ובונוס lookback מחושבים לרכישה; מכירות כמו RSU (FIFO). בגרף הראשי הערך נשאר שטוח.</p>\n<p><strong>האפליקציה אינה מחשבת מס ישראלי.</strong></p>",
  "help.cash.body": "<p>כסף שנכנס לסך התיק אך אינו קשור לשוק — חסכון, עו״ש, פיקדונות.</p>\n<p>סכומים שטוחים ב־ILS או USD (המרה דרך Yahoo / דריסה). ערכו את הסכום כשהיתרה משתנה. אין ריבית.</p>",
  "help.settings.body": "<p><strong>MONTHLY_YIELD נטו מעמלות</strong>: השאירו דלוק אלא אם יש סיבה ספציפית.</p>\n<p><strong>דריסת USDILS</strong>: קבעו שער; ריק = Yahoo.</p>\n<p><strong>ייצוא / ייבוא</strong> לגיבוי. <strong>ניקוי מטמון</strong> מוחק רק מטמוני שוק — ההחזקות נשמרות.</p>",
  "toast.exportFailed": "הייצוא נכשל",
  "status.deletingAccount": "מוחק חשבון…",
  "footer.credit": "מעקב חיסכון — תוכנה אישית ולא מסחרית. ללא שיוך למנהלי קופות, ברוקרים או ספקי נתונים.",
  "funds.saveHolding": "שמירת קופה",
  "pension.save": "שמירת פנסיה",
  "rsu.save": "שמירת מענק",
  "espp.save": "שמירת תוכנית",
  "common.searchFund": "חיפוש לפי שם, מנהל או FUND_ID",
  "common.selectedFund": "הקופה שנבחרה",
  "common.nickname": "כינוי",
  "common.balanceIls": "יתרה (₪)",
  "common.asOfPeriod": "נכון לתקופה",
  "common.netOfFees": "MONTHLY_YIELD נטו מעמלות",
  "common.tickerSearch": "טיקר (חיפוש לפי סימול או שם חברה)",
  "common.tickerSearchPlaceholder": "apple, microsoft, AAPL…",
  "rsu.nicknamePlaceholder": "הענקת Q1 2024",
  "espp.nicknamePlaceholder": "ESPP מעסיק",
  "cash.nicknamePlaceholder": "עו״ש בנק הפועלים",
  "common.loadingOption": "טוען…",
  "funds.searchHint": "כולל קופת גמל, קרן השתלמות ופוליסות חיסכון (ביטוח-נט).",
  "funds.balanceHint": "השתמשו ב-0 אם אתם רק מתחילים את הקופה.",
  "funds.anchorHint": "בחרו את החודש שאליו מתייחסת היתרה המדווחת. רוב הדוחות של גמל/פנסיה הם לסוף החודש הקודם — זו ברירת המחדל.",
  "funds.excludeFromDashboard": "הסתרה מהדשבורד",
  "funds.includeInDashboard": "הצגה בדשבורד",
  "funds.excludedBadge": "לא בדשבורד",
  "funds.excludedGroupLabel": "לא נכללות בדשבורד",
  "funds.excludedToast": "הקופה הוסתרה מסך הדשבורד",
  "funds.includedToast": "הקופה נכללת בסך הדשבורד",
  "pension.anchorHint": "אותה מוסכמת עוגן כמו בקופות. גרסה 1 אינה מודלת הפקדות שכר חוזרות — עגנו מחדש מדי פעם כשמגיע דוח חדש.",
  "rsu.grantDate": "תאריך הענקה",
  "rsu.totalShares": "סך מניות",
  "rsu.vestingStart": "תחילת הבשלה",
  "rsu.vestingMonths": "חודשי הבשלה",
  "rsu.cliffMonths": "חודשי cliff",
  "rsu.cadence": "תדירות",
  "rsu.cadence.monthly": "חודשי",
  "rsu.cadence.quarterly": "רבעוני",
  "rsu.grantPriceOverride": "דריסת מחיר הענקה (USD למניה)",
  "rsu.grantPricePlaceholder": "ריק = מחיר סגירה ביום ההענקה",
  "rsu.overrideHint": "דרסו רק אם החברה דיווחה על FMV שונה (למשל ממוצע 30 יום או ערך שאושר בדירקטוריון). השאירו ריק כדי להשתמש במחיר הסגירה של Yahoo ביום ההענקה — זהו בסיס העלות שבו משתמשים Yahoo ורוב הברוקרים בארה״ב.",
  "espp.discount": "אחוז הנחה",
  "espp.offering": "אורך מחזור (חודשים)",
  "espp.lookback": "לתוכנית יש lookback (ההנחה חלה על הנמוך מבין מחיר תחילת/סוף התקופה)",
  "cash.amount": "סכום",
  "cash.currency": "מטבע",
  "cash.note": "הערה",
  "time.never": "אף פעם",
  "time.justNow": "הרגע",
  "time.minAgo": "לפני {n} דק׳",
  "time.hAgo": "לפני {n} שע׳",
  "time.dAgo": "לפני {n} ימים",
  "api.unauthorized": "לא מורשה",
  "api.invalidJson": "תגובת JSON לא תקינה",
  "api.networkError": "שגיאת רשת",
  "api.requestFailed": "הבקשה נכשלה",
  "label.funds": "קופות",
  "label.rsu": "RSU",
  "label.espp": "ESPP",
  "label.cash": "מזומן",
  "common.add": "הוספה",
  "common.delete": "מחיקה",
  "common.note": "הערה",
  "common.kind": "סוג",
  "common.date": "תאריך",
  "common.close": "סגירה",
  "common.clear": "ניקוי",
  "chart.value": "שווי",
  "chart.fundsAtRate": "קופות (ב־{pct}%/שנה)",
  "chart.ifFundsGrow": "אם הקופות צומחות {pct}%/שנה",
  "chart.vestingAtToday": "הבשלה במחיר של היום",
  "chart.close": "{ticker} סגירה (USD)",
  "chart.purchaseDates": "תאריכי רכישה ({n})",
  "chart.analystLow": "תחזית אנליסטים נמוכה ({value})",
  "chart.analystHigh": "תחזית אנליסטים גבוהה ({value})",
  "chart.analystMean": "יעד אנליסטים ל-12 חודשים — ממוצע {value} ({analysts})",
  "chart.grantDate": "תאריך הענקה {date} ({price})",
  "chart.analystsCount": "{n} אנליסטים",
  "chart.consensus": "קונצנזוס",
  "chart.currentClose": "סגירה נוכחית",
  "chart.purchasesMarked": "{n} רכישות מסומנות",
  "chart.purchaseMarked": "{n} רכישה מסומנת",
  "chart.grantSummary": "הענקה {date}",
  "chart.analystTargetSummary": "יעד אנליסטים ל-12 חודשים",
  "chart.vsCurrent": "({sign}{pct}% מול הנוכחי)",
  "chart.rangeAnalysts": "(טווח {low}–{high}, {n} אנליסטים)",
  "chart.noAnalystTarget": "אין יעד אנליסטים זמין עבור {ticker}.",
  "chart.noAnalystTargetSparse": "אין יעד אנליסטים זמין עבור {ticker} (כיסוי דל או שליפה בהמתנה).",
  "chart.noHistory": "אין היסטוריית מחירים במטמון עבור {ticker} עדיין — לחצו רענון כדי לשלוף מ-Yahoo Finance.",
  "proj.mean": "ממוצע תחזית",
  "proj.meanDashboard": "ממוצע תחזית (~{pct}%/שנה ממוצע היסטורי לקופות{contrib})",
  "proj.meanFund": "ממוצע תחזית (~{pct}%/שנה ממוצע היסטורי{contrib}, {n} חודשים)",
  "proj.meanRsu": "ממוצע תחזית (הבשלה במחיר של היום)",
  "proj.meanEspp": "ממוצע תחזית (קבוע)",
  "proj.contribSuffix": " + הפקדות",
  "proj.rateWeighted": "הקופות צומחות ב<strong>ממוצע היסטורי משוקלל ~{pct}%/שנה</strong>",
  "proj.rateEachHolding": "הקופות משתמשות בתשואה ההיסטורית הממוצעת של כל החזקה",
  "proj.includingRecurring": " (כולל הפקדות חוזרות)",
  "dash.whatIfSummary": "<strong>אם הקופות צומחות {pct}%/שנה</strong> למשך {months} חודשים → <strong>{end}</strong> <span style=\"color:var(--color-muted)\">({sign}{delta} מהיום · מזומן + RSU + ESPP קבועים)</span>",
  "dash.projSummary": "<strong>{meanLabel}</strong> על פני {months} חודשים → <strong>{end}</strong> <span style=\"color:var(--color-muted)\">({sign}{delta} מהיום)</span>. <span style=\"color:var(--color-muted)\">{ratePart}{contrib}; כולל הבשלת RSU + ESPP/מזומן קבועים בסך.</span>",
  "dash.rangeSummary": "<strong>{start}</strong> → <strong>{end}</strong> · סך בהתחלה: <strong>{startVal}</strong> · סך בסוף: <strong>{endVal}</strong> <span style=\"color:var(--color-muted)\">({sign}{delta})</span>",
  "goal.setCta": "הגדרת יעד",
  "goal.editTitle": "עריכת היעד",
  "goal.ofTarget": "מהיעד",
  "goal.pctTitle": "החלק מהיעד שהושג עד כה (סך ההון הנוכחי ÷ סכום היעד).",
  "goal.headline": "{amount} עד {date}",
  "goal.onPace": "בקצב הנכון — צפי <strong>{projected}</strong>",
  "goal.behind": "בפיגור של כ-<strong>{gap}</strong>",
  "goal.reached": "היעד הושג! <strong>{amount}</strong>",
  "goal.datePassed": "תאריך היעד חלף — הושגו {pct}%",
  "goal.title": "הגדרת יעד חיסכון",
  "goal.blurb": "עקוב אחר סך ההון שלך לעבר סכום יעד עד חודש יעד. פנסיה אינה נכללת, בהתאם לסך הכולל בכותרת. סטטוס העמידה בקצב מחושב לפי אותה תחזית שמוצגת בגרף בלוח המחוונים.",
  "goal.amount": "סכום יעד (₪)",
  "goal.amountPlaceholder": "לדוגמה 1000000",
  "goal.date": "חודש יעד (YYYY / MM)",
  "goal.datePlaceholder": "YYYY / MM",
  "goal.dateHint": "בחר את השנה והחודש שבהם תרצה להגיע ליעד, לדוגמה 2030 / 12.",
  "goal.basis": "מבוסס על התחזית בלוח המחוונים.",
  "goal.save": "שמירת יעד",
  "goal.clear": "מחיקת יעד",
  "goal.saved": "היעד נשמר",
  "goal.cleared": "היעד נמחק",
  "goal.errAmount": "הזן סכום יעד גדול מאפס.",
  "goal.errDate": "בחר חודש יעד.",
  "detail.projCaption": "הקו המקווקו משתמש ב-~{pct}%/שנה — ממוצע של {n} תשואות חודשיות היסטוריות ממאגר הנתונים הרשמי.{contrib}",
  "detail.projCaptionContrib": " כולל את ההפקדות החוזרות שלכם בכל חודש.",
  "empty.funds.title": "אין קופות עדיין",
  "empty.funds.body": "הוסיפו קופת גמל/השתלמות/פנסיה ישראלית כדי להתחיל במעקב.",
  "empty.pension.title": "אין קרנות פנסיה עדיין",
  "empty.pension.body": "עקבו כאן אחר קרן הפנסיה (קופת פנסיה) שלכם. אותו מנגנון עוגן + תשואה חודשית כמו בקופות. לא נספר בסך לוח הבקרה.",
  "empty.rsu.title": "אין מענקי RSU עדיין",
  "empty.rsu.body": "הוסיפו מענק כדי לעקוב אחר שוויו עם הבשלה ומחירים חיים מ-Yahoo Finance.",
  "empty.espp.title": "אין תוכניות ESPP עדיין",
  "empty.espp.body": "הוסיפו תוכנית כדי לעקוב אחר רכישות, בונוסי lookback וההנחה שנתפסה בכל מחזור.",
  "empty.cash.title": "אין רשומות מזומן",
  "empty.cash.body": "הוסיפו חשבונות חיסכון, יתרות עו״ש או כל כסף לא מושקע שתרצו לספור בסך הכולל.",
  "badge.archived": "בארכיון",
  "badge.noPriceData": "אין נתוני מחיר",
  "badge.lookback": "lookback",
  "badge.rule": "כלל",
  "badge.manual": "ידני",
  "badge.auto": "אוטומטי",
  "badge.override": "דריסה",
  "badge.pending": "לא כלול ביתרה",
  "badge.pendingTip": "נרשם, אך עדיין לא נכלל בשווי או בסך הכולל — תשואת החודש טרם פורסמה. היא תיושם אוטומטית לכשתפורסם.",
  "row.last": "אחרון",
  "row.ytdAsOf": "נכון ל-{year} מתחילת השנה",
  "detail.anchorPeriod": "תקופת עוגן",
  "detail.anchorBalance": "יתרת עוגן",
  "detail.depositedTotal": "הופקד (סך הכול)",
  "detail.fromRules": "מכללים: אתם / מעסיק",
  "detail.withdrawn": "נמשך",
  "detail.mgmtFeesPaid": "~דמי ניהול ששולמו",
  "detail.mgmtFeesTitle": "דמי ניהול מצבירה — אומדן דמי הניהול המצטברים ששולמו לאורך תקופת ההחזקה (כבר מגולמים בתשואה נטו שפורסמה כברירת מחדל)",
  "detail.lastSync": "סנכרון אחרון",
  "detail.returnsChained": "תשואות (שרשור מתשואות חודשיות)",
  "detail.moreDetails": "פרטים ותשואות",
  "detail.classification": "סיווג",
  "detail.recurringContributions": "הפקדות חוזרות",
  "detail.noRecurringRule": "אין כלל חוזר. הוסיפו נקודת שינוי כדי להתחיל.",
  "detail.noRecurringRulePension": "אין כלל חוזר. הוסיפו נקודת שינוי כדי להתחיל לעקוב אחר הפקדות חודשיות (למשל הפקדות שכר לפנסיה שלכם).",
  "detail.addChangePoint": "+ הוספת נקודת שינוי",
  "detail.events": "אירועים",
  "detail.noEvents": "אין אירועים עדיין. הוסיפו כלל חוזר להפקדות חודשיות, או רשמו חד-פעמי למטה.",
  "detail.eventCaption": "להפקדות חודשיות חוזרות עם פיצול אתם/מעסיק, השתמשו בכלל חוזר למעלה. אירועים ידניים הם סכומים קבועים.",
  "rule.effectiveFrom": "בתוקף מ־",
  "rule.effectiveUntil": "בתוקף עד",
  "rule.leaveBlankOngoing": "השאירו ריק למתמשך",
  "rule.youPerMo": "אתם (₪/חודש)",
  "rule.employerPerMo": "מעסיק (₪/חודש)",
  "rule.dayOfMonth": "יום בחודש",
  "rule.saveRule": "שמירת כלל",
  "rule.setEndDate": "קביעת תאריך סיום",
  "rule.you": "אתם",
  "rule.employer": "מעסיק",
  "rule.day": "יום",
  "rule.perMo": "/חודש",
  "rule.total": "סה״כ",
  "rule.ongoing": "מתמשך",
  "table.date": "תאריך",
  "table.kind": "סוג",
  "table.amount": "סכום",
  "table.source": "מקור",
  "table.note": "הערה",
  "table.shares": "מניות",
  "table.salePrice": "מחיר מכירה",
  "table.proceeds": "תמורה",
  "table.contribution": "הפקדה",
  "table.periodStart": "תחילת תקופה",
  "table.periodEnd": "סוף תקופה",
  "table.buyPrice": "מחיר קנייה",
  "table.discountCaptured": "הנחה שנתפסה",
  "table.lookbackBonus": "בונוס lookback",
  "ev.kind.deposit": "הפקדה",
  "ev.kind.withdrawal": "משיכה",
  "ev.kind.correction": "תיקון (קביעת יתרה)",
  "ev.amountIls": "סכום (₪)",
  "action.rename": "שינוי שם",
  "action.delete": "מחיקה",
  "action.editAnchorBalance": "עריכת יתרת עוגן",
  "action.spotCheck": "בדיקת תשואה ↗",
  "action.deletePension": "מחיקת פנסיה",
  "action.edit": "עריכה",
  "action.editShares": "עריכת מניות",
  "action.setGrantPrice": "קביעת מחיר הענקה (דריסת FMV)",
  "action.editPlan": "עריכת תוכנית",
  "action.archive": "העברה לארכיון",
  "action.unarchive": "הוצאה מארכיון",
  "action.deletePlan": "מחיקת תוכנית",
  "metrics.title": "מדדי קופה (דוח אחרון)",
  "metrics.mgmtFeeAnnual": "דמי ניהול (שנתי)",
  "metrics.depositFee": "דמי ניהול מהפקדה",
  "metrics.stdDeviation": "סטיית תקן",
  "metrics.alpha": "אלפא",
  "metrics.sharpe": "שארפ",
  "metrics.stockExposure": "חשיפה למניות",
  "metrics.foreignExposure": "חשיפה למט״ח",
  "metrics.liquidAssets": "נכסים נזילים",
  "metrics.totalAssets": "סך נכסים",
  "metrics.inception": "תחילת פעילות",
  "metrics.specialization": "התמחות",
  "metrics.subSpecialization": "תת-התמחות",
  "metrics.upstreamYields": "תשואות עוקבות מגמלנט:",
  "metrics.upstream3y": "מצטבר 3ש {cum}% ({ann})",
  "metrics.upstream5y": "מצטבר 5ש {cum}% ({ann})",
  "pension.whatIfSummary": "<strong>אם הקופות צומחות {pct}%/שנה</strong> למשך {months} חודשים → <strong>{end}</strong> <span style=\"color:var(--color-muted)\">({sign}{delta} מהיום · {includes})</span>",
  "pension.includesRecurring": "כולל הפקדות חוזרות",
  "pension.noRecurring": "ללא הפקדות חוזרות",
  "pension.whatifDetail": "<strong>אם הקופות צומחות {pct}%/שנה</strong> (מקלט לוח הבקרה) → בעוד <code>{months} חודשים</code> הפנסיה הזו מגיעה ל-<strong>{end}</strong> ({sign}{delta} דטרמיניסטי). כולל את ההפקדות החוזרות למטה.",
  "rsu.heldSub": "מוחזק {held} (הובשל {vested}, נמכר {sold}) / {total}",
  "rsu.vestedSub": "הובשל {vested} / {total}",
  "rsu.granted": "הוענק {date}",
  "rsu.vestsSub": "מבשיל {months}ח, cliff {cliff}ח",
  "rsu.potential": "פוטנציאל {value}",
  "rsu.potentialTitle": "אם כל {shares} המניות היו מובשלות במחיר של היום",
  "rsu.currentPrice": "מחיר נוכחי",
  "rsu.costBasisPerShare": "בסיס עלות / מניה",
  "rsu.costBasisVested": "בסיס עלות (הובשל)",
  "rsu.grantClose": "מחיר סגירה ביום ההענקה",
  "rsu.grantUsdils": "USDILS בהענקה",
  "rsu.vestingCadence": "תדירות הבשלה",
  "rsu.fullyVestedBy": "הבשלה מלאה עד",
  "rsu.heldVestedSold": "מוחזק כעת / הובשל / נמכר",
  "rsu.potentialToday": "פוטנציאל במחיר של היום",
  "rsu.realizedGain": "רווח ממומש",
  "rsu.unrealizedGain": "רווח לא ממומש",
  "rsu.detailCaption": "\"פוטנציאל במחיר של היום\" = מניות שנותרו × מחיר של היום. רווח ממומש = (מחיר מכירה − בסיס עלות) × מניות שנמכרו, שער מתאריך המכירה. לא ממומש = (מחיר נוכחי − בסיס עלות) × מניות שעדיין מוחזקות.",
  "rsu.forecastHeading": "{ticker} מחיר ותחזית אנליסטים",
  "rsu.forecastSub": "USD · היסטוריה (6 חודשים או עד ההענקה) → יעד אנליסטים ל-12 חודשים",
  "rsu.sales": "מכירות",
  "rsu.noSales": "אין מכירות עדיין.",
  "rsu.sharesToSell": "מניות למכירה",
  "rsu.salePriceUsd": "מחיר מכירה (USD/מניה)",
  "rsu.sell": "מכירה",
  "espp.currentPrice": "מחיר נוכחי",
  "espp.discountLabel": "הנחה",
  "espp.noLookback": "ללא lookback",
  "espp.offeringLength": "אורך מחזור",
  "espp.months": "חודשים",
  "espp.totalContributed": "סך הופקד",
  "espp.sharesAcquired": "מניות שנרכשו",
  "espp.heldSold": "מוחזק / נמכר",
  "espp.costBasisHeld": "בסיס עלות (מוחזק)",
  "espp.discountCapturedLifetime": "הנחה שנתפסה (מצטבר)",
  "espp.ofWhichLookback": "מתוכה בונוס lookback",
  "espp.realizedGain": "רווח ממומש",
  "espp.unrealizedGain": "רווח לא ממומש",
  "espp.detailCaption": "<strong>הנחה שנתפסה</strong> = (מחיר סוף תקופה × מניות) − הפקדה; כולל גם את ההנחה הבסיסית וגם בונוס lookback. <strong>ממומש</strong> משתמש ב-FIFO על פני מנות רכישה ושער מתאריך המכירה. <strong>לא ממומש</strong> = (מחיר נוכחי − בסיס עלות) × מניות מוחזקות.",
  "espp.forecastSub": "USD · היסטוריה (6 חודשים או עד הרכישה הראשונה) → יעד אנליסטים ל-12 חודשים",
  "espp.purchases": "רכישות",
  "espp.noPurchases": "אין רכישות עדיין.",
  "espp.purchaseDate": "תאריך רכישה (סוף תקופה)",
  "espp.contributionUsd": "הפקדה (USD)",
  "espp.periodStartPrice": "מחיר תחילת תקופה",
  "espp.periodEndPrice": "מחיר סוף תקופה",
  "espp.autoSell": "מכירה אוטומטית בסוף התקופה",
  "espp.logPurchase": "רישום רכישה",
  "espp.deletePurchaseTitle": "מחיקת רכישה (וגם מכירת המילוי האוטומטי שלה, אם קיימת)",
  "espp.sharesHeldSub": "{n} מניות מוחזקות",
  "espp.purchasesSalesSub": "{p} · {s}",
  "espp.purchaseCount": "{n} רכישה",
  "espp.purchaseCountPlural": "{n} רכישות",
  "espp.saleCount": "{n} מכירה",
  "espp.saleCountPlural": "{n} מכירות",
  "espp.discountSub": "{pct}% הנחה{lookback} · {months} חוד׳",
  "espp.plusLookback": " + לוקבק",
  "cash.editLabel": "עריכה",
  "cash.usdilsSub": "≈ {ils} (USDILS {fx})",
  "settings.usdilsInfo": "USDILS = {rate}{override}",
  "settings.overrideSuffix": " (דריסה)",
  "settings.gemelnetAge": "מטא-דאטה של גמלנט בן {n} דקות",
  "status.addingFund": "מוסיף קופה + סנכרון ראשוני…",
  "status.addingPension": "מוסיף פנסיה + סנכרון ראשוני…",
  "status.addingGrant": "מוסיף מענק + סנכרון ראשוני…",
  "status.addingPlan": "מוסיף תוכנית + סנכרון ראשוני…",
  "status.addFailed": "ההוספה נכשלה",
  "toast.nicknameAmountRequired": "נדרשים כינוי וסכום",
  "toast.importFailed": "הייבוא נכשל",
  "toast.couldNotUpdatePassword": "לא ניתן לעדכן סיסמה",
  "toast.couldNotDeleteAccount": "לא ניתן למחוק חשבון",
  "toast.dateRequired": "נדרש תאריך",
  "toast.enterAmount": "הזינו סכום",
  "toast.balanceNonNegative": "היתרה חייבת להיות 0 או יותר",
  "toast.pickBalanceMonth": "בחרו את החודש שאליו מתייחסת היתרה",
  "toast.pickTicker": "בחרו טיקר מתוצאות החיפוש",
  "toast.dateSharesRequired": "נדרשים תאריך ומניות",
  "toast.eventAdded": "האירוע נוסף",
  "toast.ruleSaved": "הכלל נשמר",
  "toast.ruleDeleted": "הכלל נמחק",
  "toast.eventDeleted": "האירוע נמחק",
  "toast.renamed": "השם שונה",
  "toast.pensionDeleted": "הפנסיה נמחקה",
  "toast.saleSharesPriceRequired": "נדרשים תאריך, מניות ומחיר",
  "toast.saleRecorded": "המכירה נרשמה",
  "toast.saleDeleted": "המכירה נמחקה",
  "toast.purchaseFieldsRequired": "נדרשים תאריך, הפקדה ומחירי תחילת וסוף תקופה",
  "toast.loggedShares": "נרשמו {shares} מניות · נתפסו {captured}",
  "toast.lookbackHint": " (lookback +{amount})",
  "toast.purchaseDeleted": "הרכישה נמחקה",
  "toast.unarchived": "הוצא מארכיון",
  "toast.archived": "הועבר לארכיון",
  "toast.planDeleted": "התוכנית נמחקה",
  "toast.couldNotLoadPeriods": "לא ניתן לטעון תקופות",
  "toast.balanceZeroOrHigher": "היתרה חייבת להיות 0 או יותר",
  "toast.pickMonthForBalance": "בחרו את החודש שאליו מתייחסת היתרה",
  "toast.chatRequestFailed": "בקשת הצ׳אט נכשלה",
  "modal.changePassword.title": "שינוי סיסמה",
  "modal.changePassword.desc": "בחרו סיסמה חדשה עם לפחות 8 תווים.",
  "modal.changePassword.current": "סיסמה נוכחית",
  "modal.changePassword.new": "סיסמה חדשה",
  "modal.changePassword.confirm": "אישור סיסמה חדשה",
  "modal.changePassword.ok": "עדכון סיסמה",
  "modal.clearCache.title": "לנקות נתונים מהמטמון?",
  "modal.clearCache.desc": "מסיר מחירי גמלנט ו-Yahoo מהמטמון. ההחזקות, המענקים ורשומות המזומן שלכם אינם מושפעים — הרענון הבא ישלוף מחדש את נתוני השוק.",
  "modal.deleteAccount.title": "למחוק את החשבון שלך?",
  "modal.deleteAccount.desc": "פעולה זו מסירה לצמיתות את החשבון ואת כל הנתונים האישיים מהמסד — החזקות תיק, רשומות RSU/ESPP, יתרות מזומן, הגדרות ונתוני שוק במטמון. לא ניתן לבטל פעולה זו.",
  "modal.deleteAccount.confirmPw": "אשרו את הסיסמה",
  "modal.deleteAccount.confirmPwPlaceholder": "הזינו סיסמה לאישור המחיקה",
  "modal.deleteAccount.ok": "מחיקת החשבון שלי",
  "modal.deleteRule.title": "למחוק את הכלל החוזר הזה?",
  "modal.deleteRule.desc": "אירועי עבר שנוצרו מהכלל הזה ייעלמו מציר הזמן. היתרה הבסיסית לא משתנה אלא אם תעגנו מחדש.",
  "modal.setRuleEnd.title": "קביעת תאריך סיום לכלל",
  "modal.setRuleEnd.desc": "מתי הכלל צריך להפסיק לחול. השאירו ריק כדי לנקות (הכלל נשאר פתוח).",
  "modal.setRuleEnd.label": "תאריך סיום",
  "modal.deleteFund.title": "למחוק את החזקת הקופה הזו?",
  "modal.deleteFund.desc": "\"{name}\" — פעולה זו לצמיתות. אירועים וכללים חוזרים המשויכים אליה יוסרו גם הם. נתוני הגמלנט של הקופה במטמון נשמרים.",
  "modal.deleteRsu.title": "למחוק את מענק ה-RSU הזה?",
  "modal.deleteRsu.desc": "\"{name}\" ({ticker}) — פעולה זו לצמיתות. אירועי מכירה על המענק הזה יוסרו גם הם.",
  "modal.renameFund.title": "שינוי שם החזקת קופה",
  "modal.editAnchorBalance.title": "עריכת יתרת עוגן",
  "modal.editAnchorBalance.desc": "יתרת ייחוס נכון ל-{period}.",
  "modal.deletePension.title": "מחיקת החזקת פנסיה",
  "modal.deletePension.desc": "פעולה זו מסירה את ההחזקה מהמעקב שלכם. מטמון התשואות של pensia-net נשמר כך שהוספה מחדש של אותה קרן מיידית.",
  "modal.renamePension.title": "שינוי שם פנסיה",
  "modal.renameRsu.title": "שינוי שם מענק RSU",
  "modal.editCash.title": "עריכת רשומת מזומן",
  "modal.deleteCash.title": "למחוק את רשומת המזומן הזו?",
  "modal.deleteCash.desc": "\"{name}\" — פעולה זו לצמיתות.",
  "modal.editShares.title": "עריכת סך מניות",
  "modal.deleteSale.title": "למחוק את אירוע המכירה הזה?",
  "modal.deleteSale.desc": "התמורה הממומשת וספירת המניות המוחזקות יחזרו כאילו המכירה מעולם לא קרתה.",
  "modal.setGrantPrice.title": "קביעת מחיר הענקה (דריסת FMV)",
  "modal.setGrantPrice.desc": "דרסו רק אם החברה דיווחה על FMV השונה ממחיר הסגירה של Yahoo ביום ההענקה (למשל ממוצע 30 יום או ערך שאושר בדירקטוריון). השאירו ריק כדי לחזור למחיר הסגירה בשוק.",
  "modal.setGrantPrice.label": "מחיר הענקה (USD למניה)",
  "modal.setGrantPrice.placeholder": "השאירו ריק לשימוש במחיר הסגירה בשוק",
  "modal.deletePurchase.title": "למחוק את הרכישה הזו?",
  "modal.deletePurchase.desc": "כל מכירת מילוי אוטומטי המשויכת לרכישה זו תוסר גם היא.",
  "modal.deleteEsppSale.title": "למחוק את המכירה הזו?",
  "modal.editEsppPlan.title": "עריכת תוכנית",
  "modal.deleteEspp.title": "למחוק את תוכנית ה-ESPP הזו?",
  "modal.deleteEspp.desc": "כל הרכישות והמכירות יוסרו. לא ניתן לבטל פעולה זו.",
  "modal.grantPricePlaceholder": "ריק = מחיר סגירה ביום ההענקה",
  "search.failed": "החיפוש נכשל",
  "search.noMatches": "אין תוצאות.",
  "search.syncing": "מסנכרן…",
  "search.loading": "טוען…",
  "search.noData": "— אין נתונים —",
  "search.noPeriods": "— אין תקופות —",
  "search.latest": "אחרון",
  "search.clear": "ניקוי",
  "spot.title": "בדיקת תשואה",
  "spot.desc": "{name} · הזינו את היתרה בפועל בסוף החודש וראו את התשואה המשתמעת לאותו חודש. שום דבר לא נשמר.",
  "spot.currentValue": "שווי נוכחי (תחזית {source})",
  "spot.sourcePension": "pensia-net",
  "spot.sourceGemelnet": "גמלנט",
  "spot.newBalance": "יתרה חדשה (₪)",
  "spot.asOfMonth": "נכון לחודש",
  "spot.hint": "הזינו את היתרה בפועל ולחצו <strong>חישוב מחדש</strong>.",
  "spot.notSaved": "שום דבר לא נשמר. סגירת החלון מוחקת את המספרים הללו.",
  "spot.recalculate": "חישוב מחדש",
  "spot.enterPositive": "הזינו יתרה חיובית + חודש (YYYY-MM).",
  "spot.calculating": "מחשב…",
  "spot.aheadOf": "אתם מקדימים את {source}",
  "spot.behind": "אתם מפגרים אחרי {source}",
  "spot.trackingGap": "פער מעקב מול התשואה שפורסמה ({label})",
  "spot.notInCache": "התשואה שפורסמה עבור {period} עדיין לא במטמון — מוצגת רק התשואה המשתמעת למעלה.",
  "spot.mixedEvents": "ההפקדות/משיכות שלכם נופלות בתוך הפער — התשואה המשתמעת מערבבת את ההפקדות שלכם, אז התייחסו להשוואה בזהירות.",
  "spot.oneMonth": "חודש 1",
  "spot.nMonths": "{n} חודשים",
  "spot.previousValue": "שווי קודם",
  "spot.yourNewBalance": "היתרה החדשה שלכם",
  "spot.endOf": "סוף {period}",
  "spot.impliedYield": "תשואה משתמעת ל-{months}",
  "spot.perMo": " ({rate}/חודש)",
  "spot.chainedReturns": "תשואות משורשרות המסתיימות ב-{period}",
  "spot.window": "חלון",
  "spot.publishedOnly": "שפורסם בלבד",
  "spot.withNewBalance": "עם היתרה החדשה שלכם",
  "spot.ytd": "מתחילת השנה",
  "spot.ytdYear": "מתחילת השנה {year}",
  "spot.failed": "נכשל",
  "rsim.boundsDefault": "מינ׳ {min} · מקס׳ תלוי ביתרה",
  "rsim.boundsMax": "מינ׳ {min} · מקס׳ {max} (מסלול פנסיה מלאה)",
  "rsim.invalidInputs": "קלט לא תקין",
  "rsim.retirement": "פרישה:",
  "rsim.currentAge": "גיל נוכחי:",
  "rsim.multiplier": "מקדם:",
  "rsim.totalBalance": "יתרה כוללת:",
  "rsim.lockedForPension": "נעול לפנסיה",
  "rsim.cashGross": "מזומן (ברוטו)",
  "rsim.taxFreePortion": "חלק פטור ממס",
  "rsim.taxablePortion": "חלק חייב במס",
  "rsim.estTax": "אומדן מס (~35%)",
  "rsim.cashNet": "מזומן (נטו)",
  "rsim.lockedMakifa": "נעול (מקיפה)",
  "rsim.mashlimaCash": "מזומן משלימה",
  "rsim.mashlimaCashGross": "מזומן משלימה (ברוטו)",
  "rsim.mashlimaCashNet": "מזומן משלימה (נטו)",
  "rsim.path1": "מסלול 1 — פנסיה מלאה",
  "rsim.path2": "מסלול 2 — מקס׳ מזומן (מינ׳ פנסיה)",
  "rsim.path3": "מסלול 3 — יעד הפנסיה שלך",
  "rsim.path4": "מסלול 4 — מזומן משלימה, מקס׳ פנסיה ממקיפה",
  "rsim.monthlyPension": "פנסיה חודשית",
  "rsim.monthlyPensionMakifa": "פנסיה חודשית (מקיפה)",
  "rsim.lumpSum": "סכום חד-פעמי",
  "rsim.err.birthRequired": "נדרש תאריך לידה",
  "rsim.err.ageRange": "גיל הפרישה חייב להיות בין 55 ל-75",
  "rsim.err.positiveBalance": "הזינו לפחות יתרה חיובית אחת (מקיפה או משלימה)",
  "rsim.err.targetExceeds": "יעד פנסיה של ₪{target} דורש ₪{locked} נעולים — יותר מהיתרה הכוללת שלכם.",
  "rsim.warn.earlyRetirement": "פרישה לפני גיל {age} עלולה לגרור קנס של {penalty}% על משיכות מסוימות (היוון קצבה). הסימולטור אינו מודל את הקנס הזה על הסכומים למטה.",
  "rsim.warn.balanceTooLow": "היתרה נמוכה מדי למסלול 2 (נעילת הפנסיה המינימלית עולה על היתרה הכוללת).",
  "rsim.warn.path4NoMakifa": "מסלול 4: אין יתרת מקיפה — הפנסיה החודשית היא ₪0; כל המשלימה נמשכת כמזומן.",
  "rsim.month.1": "ינואר",
  "rsim.month.2": "פברואר",
  "rsim.month.3": "מרץ",
  "rsim.month.4": "אפריל",
  "rsim.month.5": "מאי",
  "rsim.month.6": "יוני",
  "rsim.month.7": "יולי",
  "rsim.month.8": "אוגוסט",
  "rsim.month.9": "ספטמבר",
  "rsim.month.10": "אוקטובר",
  "rsim.month.11": "נובמבר",
  "rsim.month.12": "דצמבר",
  "doc.title": "מעקב חיסכון",
};

